application:
  subdomain: axonhub
  background_task: true
  public_path:
    - /

  upstreams:
    - location: /
      backend: http://axonhub:{{.U.server_port}}/

services:
  axonhub:
    # looplj/axonhub:v0.9.35
    image: registry.lazycat.cloud/czyt/looplj/axonhub:519beaea8895ae45
    container_name: axonhub
    environment:
      # 数据库配置 - 用户可配置
      - AXONHUB_DB_DIALECT={{.U.db_dialect}}
      - AXONHUB_DB_DSN={{.U.db_dsn}}
      # 服务配置
      - AXONHUB_SERVER_PORT={{.U.server_port}}
      # 日志配置
      - AXONHUB_LOG_LEVEL={{.U.log_level}}
      - AXONHUB_LOG_ENCODING={{.U.log_encoding}}
    binds:
      - /lzcapp/var/data:/data
      - /lzcapp/var/config:/config
    healthcheck:
      test:
        - CMD-SHELL
        - "wget --no-verbose --tries=1 --spider http://localhost:{{.U.server_port}}/health"
      start_period: 30s
      timeout: 40s
    setup_script: |
      if [ ! -f /lzcapp/var/config/config.yaml ]; then
         if [ -f /app/config.yaml ]; then
             cp -r /app/config.yaml /lzcapp/var/config/config.yaml
             rm /app/config.yaml
             ln -s /lzcapp/var/config/config.yaml /app/config.yaml
         fi
      fi
